version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - node_network
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node_network
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    tty: true
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nodedb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - node_network
volumes:
  mysql_data:
networks:
  node_network:
    name: node_network
